### PR TITLE
Add Chinese Translation

### PR DESCRIPTION
**Pull request by qiansen1386**
Hi Xue Qiang, please have a look and do not merge it at this moment. As in I am about to polish it and remove all the original English words in a while.

### CODE REVIEW

**Comment by qiangxue** [comment]
Looks great to me! Thanks.

**Comment by qiansen1386** [comment]
All Done! :smile_cat:

**Comment by qiansen1386** [comment]
Actually I have completed the draft translations for [Config-gist](https://gist.github.com/qiansen1386/fbf342500b44998e89c2) and [Routing-gist](https://gist.github.com/qiansen1386/fb4be5e3be35ce1a501e) packages.

But seems you have enhanced the implementation of routing package significantly, so I will submit the translation of config packages first. I like your No-More-Magic idea, especially in routing. :+1: Thanks 强哥

**Comment by qiangxue** [comment]
Thanks!

Yes, the routing package was completely rewritten. It contains no magic now. It is one of the fastest HTTP routers but is still feature rich.

**Pull request merged**
